from fyersModel1 import FyersModelv3
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)
# # client_id= ""
# access_token ="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2xvZ2luLmZ5ZXJzLmluIiwiaWF0IjoxNjgxNzkwNDY5LCJleHAiOjE2ODE4NjQyMDksIm5iZiI6MTY4MTc5MDQ2OSwiYXVkIjpbIng6MCJdLCJzdWIiOiJhY2Nlc3NfdG9rZW4iLCJhdF9oYXNoIjoiZ0FBQUFBQmtQaFlGd2ZFb25NS3Q3S0I5TDlZX1haWWVFWXdmdXZzVFNCQ3ZuanQtSDlPcFpDRHBISVR0UEc3c3RhdUIyNHQ4cFRIWThtSWl6U1R6UGpERkgzWnMtR1pRTkR6ME5xak5SVWQ1RFRPem4wQnRrQm89IiwiZGlzcGxheV9uYW1lIjoiVklOQVkgS1VNQVIgTUFVUllBIiwiZnlfaWQiOiJYVjIwOTg2IiwiYXBwVHlwZSI6IiIsIm9tcyI6IksxIiwicG9hX2ZsYWciOiJOIiwiaHNtX2tleSI6IjNmZDVjYWVmZWI2NjI5MzFjNjU2MGNmNTk5MWI1NWUzMjdmMzNkZGY4Y2EwYjJhMWIwZWQ3MTY1In0.vwxhyKVluhXTwh3XXE6R4gCkL1Oa7QLCykELuF58dvU"
access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE2ODE3OTUyNzIsImV4cCI6MTY4MTg2NDIxMiwibmJmIjoxNjgxNzk1MjcyLCJhdWQiOlsieDowIiwieDoxIiwieDoyIiwiZDoxIiwiZDoyIiwieDoxIiwieDowIl0sInN1YiI6ImFjY2Vzc190b2tlbiIsImF0X2hhc2giOiJnQUFBQUFCa1BpaklCYkR3UHY2ZVJqeWJNQVNEdnlNU19zaGVHY1Y0cDNwVDc5cG5BUzRsNVlLbGYtdWdmZ29RM2RkamFyb1FrS0ZzQmZ3MGdMNGdRbHhweWg4S0pIcmRYXzB6M3lGUkhGWDctOXl0YlBUdVZQMD0iLCJkaXNwbGF5X25hbWUiOiJWSU5BWSBLVU1BUiBNQVVSWUEiLCJvbXMiOiJLMSIsImZ5X2lkIjoiWFYyMDk4NiIsImFwcFR5cGUiOjEwMCwicG9hX2ZsYWciOiJOIn0.nZVld-qipGF0hmAMUEkojHfy5jvssZoo4tdSvO6xRh0"

# The app id we get after creating the app
client_id = "XC4EOD67IM-100"
fyers = FyersModelv3(client_id = client_id,token=access_token,is_async=True)
print(fyers.orderbook(data={"id":"23041800142230"}))
print(fyers.quotes(data={"symbols":"NSE:IDEA-EQ"}))
print(fyers.tradebook())
# print(fyers.orderbook())
